config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  root "recipes#index"

  resources :ingredients
  resources :recipes do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :recipe
  validates_presence_of :content
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments
  
  validates_presence_of :name

  def ingredients_attributes=(ingredients_attributes)
    ingredients_attributes.each do |ingredient_attributes|
      unless ingredient_attributes["name"].blank?
        ingredient_to_add = Ingredient.find_or_create_by(name: ingredient_attributes["name"].downcase)
        self.recipe_ingredients.build(ingredient: ingredient_to_add)
      end
    end
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @comment = @recipe.comments.build(comment_params)

    if @comment.save
      render 'create.js', layout: false
    else
      render 'recipes/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def show
    @ingredient = Ingredient.find(params[:id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
    @comment = Comment.new
    @comments = @recipe.comments
  end

  def new
    @recipe = Recipe.new
  end

  def create

    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe
    else
      render :new
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, ingredients_attributes: [:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<li><%= comment.content %></li>  

app/views/comments/_comments.html.erb
<ul>
  <% @comments.each do |comment| %>
    <li><%= comment.content %></li>
  <% end %>
</ul>

app/views/comments/create.js.erb
$("#comment_content").val("");
var $ul = $("div#comments ul");
$ul.append("<%=j(render('comments/comment', :comment => @comment)) %>");

app/views/ingredients/_show.html.erb
<ul>
  <% @ingredient.recipes.each do |recipe| %>
    <li><%= link_to recipe.name, recipe_path(recipe) %></li>
  <% end %>
</ul>

app/views/ingredients/show.js.erb
$("#other_recipes").html("<%= j(render 'show') %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p>
  <%= yield %>
</p>

</body>
</html>

app/views/recipes/index.html.erb
<h2>All Recipes</h2>
<ul>
  <% @recipes.each do |recipe| %>
    <li><%= link_to recipe.name, recipe_path(recipe) %></li>
  <% end %>
</ul>

app/views/recipes/new.html.erb
<%= form_for @recipe do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <fieldset id="ingredient_fields">
    <legend>Ingredients</legend>
    <input type="text" name="recipe[ingredients_attributes][][name]">
  </fieldset>
  <%= f.submit %>
<% end %>

<p><button id="add_ingredient_field">Additional Ingredient</button></p>

<div class="recipe_display">

</div>

app/views/recipes/show.html.erb
<%= @recipe.name %>

<ul>
  <% @recipe.ingredients.each do |ingredient| %>
    <li><%= link_to ingredient.name, ingredient_path(ingredient), remote: true %></li>
  <% end %>
</ul>


<h4>Recipes with this ingredient</h4>
<div id="other_recipes">
</div>

<h4>Recipe Comments</h4>

<%= form_for [@recipe, @comment], remote: true do |f| %>
    <%= f.text_area :content %>
    <br>
    <%= f.submit %>
<% end %>

<div id="comments">
  <%= render 'comments/comments' %>
</div>